### PR TITLE
[93] ensure successful building and testing (master)

### PR DESCRIPTION
**Pull request by d-w-moore**
(cherry-picked from 4-2-11 release , #94 )

All OSes:
  glob pattern matching working for new package names

Centos:
  update ca-certificates package so that RENCI repo is recognized
  eliminate shared system dirs from RPM package

We also found CMake's demands on libssl version (=libssl.so.1.1)
are not satisfied by Ubuntu 16.

### CODE REVIEW

**Comment by trel** [comment]
yes, please # if building/good.

**Comment by d-w-moore** [comment]
CentOS 7 isn't building an irods-server package in master right now, But this passes on master for Ub18

**Comment by trel** [comment]
i think you're conflating two masters...?

so rest_cpp master branch (this PR)
is working against ub18 irods-server master.
and...
not working against cen7 irods-server master b/c... that, itself, isn't building...
?

**Comment by d-w-moore** [comment]
No this is the same problem I encountered in indexing : the Jenkins build_irods_on_base workflow does not produce an irods-server RPM. (Nor does it print any kind of error indication, the server package just isn't there.) So for the same reason we couldn't merge in indexing, we also can't merge here right now....

**Comment by trel** [comment]
okay

**Comment by alanking** [comment]
Has this been superceded by the dockerizing effort?

**Comment by trel** [comment]
i believe so for now - a test plan would be pure curl calls, and we're not there yet.    and the dockerization means we don't need multiple specific packages at this time.

**Pull request closed without merging**
