### PR TITLE
[25] exclude system and irods directories from install - master

### PR DESCRIPTION
**Pull request by d-w-moore**
Do not overwrite directories (and their permissions) shared by other packages, and especiallly do not make /var/lib/irods owned by root.

### CODE REVIEW

**Comment by trel** [comment]
so, without this, we were overwriting these perms?

**Comment by d-w-moore** [comment]
Yes, it was most obvious with /var/lib/irods becoming root/root owned.

**Comment by trel** [comment]
whew.  okay.   yes, please # it up.

**Comment by trel** [comment]
sorry, didn't know it had been #'d.   please leave a comment and i'll see it.

**Pull request merged**
