### PR TITLE
version bump to 4.2.9

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Comment by trel** [comment]
i think the nanodbc package now handles this dependency correctly, ... should check with the 429 dependency first.

**Comment by d-w-moore** [comment]
May have to move to an alternative way of detecting dependencies.  I know our older pipelines use `gdebi`.  Centos 7 has `yum local install` ... discussion time

**Comment by d-w-moore** [comment]
Ok, improved the handling of this by detecting any and all externals' deps when necessary.
All tests pass on rest C++ client in CI,  ready for merge....

**Comment by d-w-moore** [comment]
moving the externals pre-req testing to another branch for separate PR

**Comment by trel** [comment]
okay, so this is just getting to 4.2.9.    ready for merge?

**Comment by d-w-moore** [comment]
Yes. Will # then ...

**Pull request merged**
