### PR TITLE
Increased maximum request buffer size for stream endpoint (main)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by trel** [comment]
I think this is proven to be safe/good.   Please mark as ready for review and get an issue number...

**Comment by korydraughn** [comment]
The request buffer size is set to a max of 100MB. We should consider lowering that value.

Perhaps somewhere between 1MB and 8MB?

**Comment by korydraughn** [comment]
I think we need to start with a smaller value to avoid memory issues when dealing with a large number of users.

The design of the API requires users to deal with chunking (not http chunking) for the most part.

**Comment by trel** [comment]
Fair enough - pick a number.

**Comment by trel** [comment]
in the commit message...    "request to 4096" -> "request to 4096 bytes"

**Comment by korydraughn** [comment]
Changed max size to 8MB.

Ignoring clang-format. Given the switch from spaces to tabs, we're better off formatting the whole project rather than one line.

> in the commit message... "request to 4096" -> "request to 4096 bytes"

Will fix.

**Comment by korydraughn** [comment]
Updated commit message.

**Comment by trel** [comment]
looks good - please # it.

**Comment by korydraughn** [comment]
#'d

**Pull request merged**
