### PR TITLE
[181] add leading slash to constructed /query links

### PR DESCRIPTION
**Pull request by trel**

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Changes look good. Does it do what you expect now?

**Review by alanking — COMMENTED** [review]
The tests are adding the slash to the base URL itself, which is probably how this went undetected:
https://github.com/irods/irods_client_rest_cpp/blob/0c8c7997519523f6580f5fad5238229d088632e4/packaging/irods_rest.py#L17

Did something change such that the base URL stopped getting the slash? Wonder how long it's been this way...

The change seems fine, I just wonder if anything else is affected?

**Comment by korydraughn** [comment]
Looking back at version 0.8.0, it appears the slash has always been missing.

**Comment by korydraughn** [comment]
Has this been tested?

https://github.com/irods/irods_client_rest_cpp#running-test-suite

**Comment by trel** [comment]
one failure...

```
irods-client-rest-cpp_1  | <__main__.RegisteredTestResult run=1 errors=0 failures=1>
irods-client-rest-cpp_1  | irods.test.test_irods_client_rest_cpp.TestClientRest.test_add_and_remove_metadata_on_collection__issue_118 ... FAIL
irods-client-rest-cpp_1  |                                                                                                                                             
irods-client-rest-cpp_1  | ======================================================================                                                                      
irods-client-rest-cpp_1  | FAIL: test_add_and_remove_metadata_on_collection__issue_118 (irods.test.test_irods_client_rest_cpp.TestClientRest)
irods-client-rest-cpp_1  | ----------------------------------------------------------------------
irods-client-rest-cpp_1  | Traceback (most recent call last):
irods-client-rest-cpp_1  |   File "/var/lib/irods/scripts/irods/test/test_irods_client_rest_cpp.py", line 321, in test_add_and_remove_metadata_on_collection__issue_118
irods-client-rest-cpp_1  |     self.assertEqual(res, '')
irods-client-rest-cpp_1  | AssertionError: '<html>\r\n<head><title>400 Bad Request</t[126 chars]\r\n' != ''
irods-client-rest-cpp_1  | - <html>
irods-client-rest-cpp_1  | - <head><title>400 Bad Request</title></head>                                                                                               
irods-client-rest-cpp_1  | - <body>                                                                                                                                    
irods-client-rest-cpp_1  | - <center><h1>400 Bad Request</h1></center>
irods-client-rest-cpp_1  | - <hr><center>nginx/1.23.1</center>                     
irods-client-rest-cpp_1  | - </body>                                                                                                                                   
irods-client-rest-cpp_1  | - </html>                                                                                                                                   
```

investigating.

**Comment by trel** [comment]
not obvious.   please help if inclined.

**Comment by trel** [comment]
I don't think I have the test suite configured quite correctly.

No other tests run - and I'm not convinced the tests are seeing the iRODS server.

The server logs are empty after the initialization and delay server wakeup.

**Comment by korydraughn** [comment]
Okay. I'll plan to look into this today and see if I can figure out what is happening.

**Comment by korydraughn** [comment]
After some tweaks to the codebase, I was finally able to run the tests against this PR.

All tests passed.

Now the question is, is this targeting 4.3.0 or 4.3.1? If we target 4.3.1, then your change can go in as is. If we're targeting 4.3.0, then we have to revert a commit. In either case, we have to apply the tweaks I made locally.

Thoughts?

**Comment by trel** [comment]
This is going to be the last release of rest cpp... so I think we want it to work when talking to older iRODS servers too?

But building this is independent of which iRODS server it talks to...

**Comment by korydraughn** [comment]
Understood. The issue I'm bringing forward has to do with testing though.

Right now, the test suite is broken. It runs 4.3.0 python code which is incompatible with Nishant's latest commit. There are a few more tweaks that need to be made to fix the tests.

Regardless, your PR is fine to merge as is.

**Review by korydraughn — APPROVED** [review]

**Comment by trel** [comment]
okay, got it, thanks.

added the #.

ready for merge.

**Pull request merged**
