### PR TITLE
[#76, #77] Fix package filename and set IRODS_MACRO_CHECK_DEPENDENCY_SET_FULLPATH (4-2-stable)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
The second commit in this PR should be reverted once `4-2-stable` is no longer targeting as-released 4.2.10.

### CODE REVIEW

**Comment by trel** [comment]
not there yet...
```
irods-client-rest-cpp_~bionic_amd64.deb
```

**Comment by SwooshyCueb** [comment]
Apologies, I'm not currently set up to build anything requiring an unpackaged extern in a container so I can't test packaging changes.
If you comment out lines 238 and 241, does the name come out properly?

**Comment by trel** [comment]
cleared all cmake files, rebuilt....  no, same.

**Comment by SwooshyCueb** [comment]
Should be working now

**Comment by trel** [comment]
behold...

```
irods-client-rest-cpp_0.8.0~bionic_amd64.deb
```

yes, please # em and we'll get some externals updated and this thing released.

**Pull request merged**
