### PR TITLE
prepare 0.9.3

### PR DESCRIPTION
**Pull request by trel**

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
The files under `docker/tester` and `docker/runner` could be updated as well, but aren't really part of the release, technically

**Comment by alanking** [comment]
Looks good to me. Squash and #

**Comment by trel** [comment]
you'd prefer a single commit vs these three?

**Comment by alanking** [comment]
Nope, 3 is good

**Comment by trel** [comment]
pushed and #'d.

**Pull request merged**
